// Source data for the AI Prompt Bank wizard.

export const ASPECTS = [
    { id: "vocabulary",  emoji: "Aa", labelEn: "Vocabulary", labelUk: "Лексика",
      descEn: "Words, collocations, business phrases.",     descUk: "Слова, колокації, фрази." },
    { id: "listening",   emoji: "(()", labelEn: "Listening", labelUk: "Аудіювання",
      descEn: "Understanding spoken English.",              descUk: "Розуміння на слух." },
    { id: "reading",     emoji: "¶", labelEn: "Reading",    labelUk: "Читання",
      descEn: "Comprehending texts and reports.",           descUk: "Читання й розуміння текстів." },
    { id: "speaking",    emoji: "“ ”", labelEn: "Speaking", labelUk: "Говоріння",
      descEn: "Saying it out loud — in calls, in meetings.", descUk: "Усне мовлення." },
    { id: "writing",     emoji: "✎", labelEn: "Writing",    labelUk: "Письмо",
      descEn: "Emails, messages, structured text.",         descUk: "Листи, повідомлення, тексти." },
    { id: "grammar",     emoji: "[ ]", labelEn: "Grammar",  labelUk: "Граматика",
      descEn: "Tenses, conditionals, structures in context.", descUk: "Граматичні структури." },
    { id: "translation", emoji: "↹", labelEn: "Translation", labelUk: "Переклад",
      descEn: "Compare L1 ↔ L2, notice differences.",       descUk: "Порівняння L1 ↔ L2." },
    { id: "custom",      emoji: "?", labelEn: "Something else", labelUk: "Своє",
      descEn: "Describe what you want to train.",           descUk: "Опиши, що хочеш тренувати." },
];

export const TOPIC_PLACEHOLDERS = {
    vocabulary: { en: "e.g. Phrases for giving feedback, collocations for client calls",
                  uk: "напр. Фрази для фідбеку, колокації для дзвінків з клієнтами" },
    listening:  { en: "e.g. Following a fast-paced product demo",
                  uk: "напр. Слухати швидкі демо продуктів" },
    reading:    { en: "e.g. Skimming a tech research paper",
                  uk: "напр. Швидко читати технічну статтю" },
    speaking:   { en: "e.g. Running a client call, presenting quarterly results",
                  uk: "напр. Вести дзвінок з клієнтом, презентувати квартальні результати" },
    writing:    { en: "e.g. Writing escalation emails, polite refusals",
                  uk: "напр. Писати ескалаційні листи, ввічливі відмови" },
    grammar:    { en: "e.g. Present Perfect in emails, conditionals for requests",
                  uk: "напр. Present Perfect у листах, умовні для запитів" },
    translation:{ en: "e.g. How «зручно» maps to English",
                  uk: "напр. Як «зручно» перекладається англійською" },
    custom:     { en: "e.g. Pronouncing TH sounds when stressed",
                  uk: "напр. Вимовляти TH під стрес" },
};

export const LEVELS = [
    { id: "A1",  label: "A1",  descEn: "Beginner",   descUk: "Початковий" },
    { id: "A2",  label: "A2",  descEn: "Elementary", descUk: "Основи" },
    { id: "A2+", label: "A2+", descEn: "Pre-Int",    descUk: "До-середній" },
    { id: "B1",  label: "B1",  descEn: "Intermediate", descUk: "Середній" },
    { id: "B1+", label: "B1+", descEn: "Upper-Int",  descUk: "Вище середнього" },
    { id: "B2",  label: "B2",  descEn: "Advanced",   descUk: "Просунутий" },
    { id: "C1",  label: "C1",  descEn: "Proficient", descUk: "Майстерний" },
    { id: "C2",  label: "C2",  descEn: "Mastery",    descUk: "Володіння" },
];

export const ENERGIES = [
    { id: "easy",      glyph: "○" },
    { id: "normal",    glyph: "◐" },
    { id: "challenge", glyph: "●" },
];

// Bloom labels adapt per aspect.
export const BLOOM_STAGES = ["remember", "understand", "apply_controlled", "apply_free", "evaluate", "create"];

export const BLOOM_LABELS = {
    vocabulary: {
        remember:         { en: "Meet new words",                uk: "Познайомитись зі словами" },
        understand:       { en: "Understand how to use them",    uk: "Зрозуміти, як їх вживати" },
        apply_controlled: { en: "Practise with support",         uk: "Практика з підтримкою" },
        apply_free:       { en: "Use them on my own",            uk: "Вживати самостійно" },
        evaluate:         { en: "Check what I remember",         uk: "Перевірити, що памʼятаю" },
        create:           { en: "Use in a real situation",       uk: "Застосувати в реальній ситуації" },
    },
    listening: {
        remember:         { en: "Tune my ear to the topic",       uk: "Налаштувати слух на тему" },
        understand:       { en: "Catch the gist and key points",  uk: "Схопити суть і ключові моменти" },
        apply_controlled: { en: "Listen and notice with prompts", uk: "Слухати і помічати з підказками" },
        apply_free:       { en: "Follow without subtitles",       uk: "Слухати без субтитрів" },
        evaluate:         { en: "Check what I missed",            uk: "Перевірити, що пропустив" },
        create:           { en: "Engage live in a conversation",  uk: "Реагувати наживо в розмові" },
    },
    reading: {
        remember:         { en: "Skim and recognise structure",   uk: "Перегляд і впізнавання структури" },
        understand:       { en: "Understand the argument",        uk: "Зрозуміти аргумент" },
        apply_controlled: { en: "Read with guided questions",     uk: "Читання з питаннями" },
        apply_free:       { en: "Read independently",             uk: "Читати самостійно" },
        evaluate:         { en: "Find what I misunderstood",      uk: "Знайти, що зрозумів не так" },
        create:           { en: "Use the text in my work",        uk: "Використати текст у роботі" },
    },
    speaking: {
        remember:         { en: "Hear how it sounds first",       uk: "Спершу почути, як це звучить" },
        understand:       { en: "Understand what to say and when", uk: "Зрозуміти, що й коли казати" },
        apply_controlled: { en: "Rehearse phrases with guidance", uk: "Репетирувати фрази з підказками" },
        apply_free:       { en: "Speak freely without a script",  uk: "Говорити вільно, без скрипту" },
        evaluate:         { en: "Find what sounds unnatural",     uk: "Помітити, що звучить неприродно" },
        create:           { en: "Have a real conversation",       uk: "Провести реальну розмову" },
    },
    writing: {
        remember:         { en: "See examples of the genre",      uk: "Побачити приклади жанру" },
        understand:       { en: "Understand the moves",           uk: "Зрозуміти структуру ходів" },
        apply_controlled: { en: "Write with a template",          uk: "Писати за шаблоном" },
        apply_free:       { en: "Write on my own",                uk: "Писати самостійно" },
        evaluate:         { en: "Find weak spots in my draft",    uk: "Знайти слабкі місця в чернетці" },
        create:           { en: "Send it for real",               uk: "Надіслати по-справжньому" },
    },
    grammar: {
        remember:         { en: "See the structure in context",   uk: "Побачити структуру в контексті" },
        understand:       { en: "Understand when to use it",      uk: "Зрозуміти, коли вживати" },
        apply_controlled: { en: "Practise with controlled drills", uk: "Тренуватись на контрольованих вправах" },
        apply_free:       { en: "Use it in my own sentences",     uk: "Вживати у власних реченнях" },
        evaluate:         { en: "Spot my own mistakes",           uk: "Помітити свої помилки" },
        create:           { en: "Apply it in real writing/speech", uk: "Застосувати у листах/мовленні" },
    },
    translation: {
        remember:         { en: "See L1 ↔ L2 pairs",              uk: "Побачити L1 ↔ L2 пари" },
        understand:       { en: "Understand why they differ",     uk: "Зрозуміти, чому різниця" },
        apply_controlled: { en: "Translate with hints",           uk: "Перекладати з підказками" },
        apply_free:       { en: "Translate on my own",            uk: "Перекладати самостійно" },
        evaluate:         { en: "Find translation traps",         uk: "Помітити пастки перекладу" },
        create:           { en: "Translate something I'll use",   uk: "Перекласти те, що використаю" },
    },
    custom: {
        remember:         { en: "Discover the material",          uk: "Познайомитись із матеріалом" },
        understand:       { en: "Understand it in context",       uk: "Зрозуміти в контексті" },
        apply_controlled: { en: "Practise with support",          uk: "Практика з підтримкою" },
        apply_free:       { en: "Apply on my own",                uk: "Застосувати самостійно" },
        evaluate:         { en: "Check what's still weak",        uk: "Перевірити слабкі місця" },
        create:           { en: "Use it in a real situation",     uk: "Використати в реальній ситуації" },
    },
};

// Each activity has:
//   what — what it actually is (the AI-tool feature)
//   how  — how it serves English learning specifically
export const ACTIVITIES = [
    {
        id: "audio_retelling", glyph: "♪", tool: "notebooklm",
        labelEn: "Audio Overview (podcast)", labelUk: "Audio Overview (подкаст)",
        whatEn: "NotebookLM Studio generates an interactive AI podcast on your sources — you can even join live and ask questions.",
        whatUk: "NotebookLM Studio робить інтерактивний AI-подкаст за твоїми джерелами — можна підключитись наживо й питати.",
        howEn: "Listen with subtitles off, then retell using your own phrases. Strongest for listening + speaking.",
        howUk: "Слухай без субтитрів, потім перекажи своїми словами. Найкраще для аудіювання + говоріння.",
    },
    {
        id: "video_retelling", glyph: "▷", tool: "notebooklm",
        labelEn: "Video Overview (visual explainer)", labelUk: "Video Overview (відео-пояснення)",
        whatEn: "A narrated AI video that explains the topic with diagrams and on-screen text.",
        whatUk: "AI-відео з діаграмами та підписами, яке візуально пояснює тему.",
        howEn: "First watch without subtitles for gist; second pass with subtitles to notice phrases. Then explain back.",
        howUk: "Спершу без субтитрів — для суті; потім із субтитрами — помічаєш фрази. Потім поясни тему своїми словами.",
    },
    {
        id: "mind_map", glyph: "◯", tool: "notebooklm",
        labelEn: "Mind Map", labelUk: "Mind Map",
        whatEn: "Clickable concept map: central topic + branches with connected ideas, vocabulary, and sub-questions.",
        whatUk: "Клікабельна мапа концепту: центральна тема + гілки зі звʼязаними ідеями, лексикою, під-питаннями.",
        howEn: "Organise vocabulary by meaning groups; turn each branch into a 60-second speaking prompt.",
        howUk: "Групуй лексику за значенням; перетвори кожну гілку на 60-секундну тему для говоріння.",
    },
    {
        id: "flashcards", glyph: "▭", tool: "notebooklm",
        labelEn: "Flashcards (term · translation · example)", labelUk: "Flashcards (слово · переклад · приклад)",
        whatEn: "Auto-generated cards. Pick the format: term ↔ translation, term ↔ definition, or term ↔ example sentence with a gap.",
        whatUk: "Авто-картки. Обери формат: слово ↔ переклад, слово ↔ означення, або речення з пропуском.",
        howEn: "Active recall — front in your L1, back in English (or reverse). Best for vocabulary + collocations.",
        howUk: "Активне пригадування — перед українською, зворот англійською (або навпаки). Топ для лексики + колокацій.",
    },
    {
        id: "test", glyph: "?", tool: "notebooklm",
        labelEn: "Quiz / Test", labelUk: "Тест / Quiz",
        whatEn: "Auto-generated quiz — mix of multiple-choice and open questions tied to your sources.",
        whatUk: "Авто-тест — мікс з вибором відповіді й відкритих питань на матеріалі твоїх джерел.",
        howEn: "Take it after study with no notes (retrieval practice — Roediger). Identifies what hasn't stuck yet.",
        howUk: "Пиши без нотаток (retrieval practice — Roediger). Покаже, що ще не закріпилось.",
    },
    {
        id: "infographic", glyph: "▤", tool: "notebooklm",
        labelEn: "Infographic", labelUk: "Інфографіка",
        whatEn: "A single-page visual summary — vocabulary, structure, examples on one screen.",
        whatUk: "Одна сторінка візуального підсумку — лексика, структура, приклади на одному екрані.",
        howEn: "Pin to your desktop. Use as a 30-second 'before-the-meeting' refresher.",
        howUk: "Закріпи на робочому столі. Юзай як 30-секундне нагадування перед зустріччю.",
    },
    {
        id: "study_guide", glyph: "≡", tool: "notebooklm",
        labelEn: "Study Guide", labelUk: "Study Guide",
        whatEn: "Structured guide (Q&A or chapter format) — your personal textbook on the topic.",
        whatUk: "Структурований посібник (Q&A або розділи) — твій персональний підручник з теми.",
        howEn: "Read-through then close it and try to reproduce key phrases out loud.",
        howUk: "Прочитай, закрий і спробуй вголос відтворити ключові фрази.",
    },
    {
        id: "presentation", glyph: "▥", tool: "notebooklm",
        labelEn: "Presentation", labelUk: "Презентація",
        whatEn: "Slide deck explaining the topic — built from your sources.",
        whatUk: "Слайд-презентація теми — за твоїми джерелами.",
        howEn: "Present it aloud as if pitching to a colleague. Record yourself, then ask AI to grade tone & clarity.",
        howUk: "Презентуй уголос, наче колезі. Запиши себе, попроси AI оцінити тон і ясність.",
    },
    {
        id: "roleplay", glyph: "▲", tool: "chatgpt_gemini",
        labelEn: "Roleplay / Dialogue", labelUk: "Роуплей / діалог",
        whatEn: "AI plays one role (client, manager, customer), you play another. Real-life business scenarios.",
        whatUk: "AI грає одну роль (клієнт, менеджер, замовник), ти — іншу. Реальні бізнес-сценарії.",
        howEn: "Paste target phrases from NotebookLM so AI uses ONLY them. Best for Speaking + Business English.",
        howUk: "Встав цільові фрази з NotebookLM, щоб AI вживав ТІЛЬКИ їх. Топ для Speaking + Business English.",
    },
    {
        id: "speak_voice", glyph: "✦", tool: "chatgpt_gemini",
        labelEn: "Voice chat (live)", labelUk: "Голосовий чат (наживо)",
        whatEn: "Real-time voice conversation with ChatGPT Voice or Gemini Live — speak, AI replies in audio.",
        whatUk: "Голосова розмова з ChatGPT Voice або Gemini Live — говориш, AI відповідає голосом.",
        howEn: "Train pronunciation + fluency + live reaction. Ask AI to gently recast your errors.",
        howUk: "Тренуй вимову + побіжність + живу реакцію. Попроси AI мʼяко переформульовувати помилки.",
    },
    {
        id: "write_feedback", glyph: "✎", tool: "chatgpt_gemini",
        labelEn: "Write + feedback", labelUk: "Письмо + фідбек",
        whatEn: "Write a short text (email, paragraph, post) — AI gives line-by-line corrections + clean rewrite.",
        whatUk: "Напиши короткий текст (лист, абзац, пост) — AI дає правки рядок-за-рядком + чисту переписану версію.",
        howEn: "Best for emails, business writing, posts. Compare your version vs. clean rewrite — note 3 patterns.",
        howUk: "Топ для листів, бізнес-письма, постів. Порівняй свій варіант з чистим — виділи 3 патерни.",
    },
    {
        id: "claude_chat", glyph: "✶", tool: "claude",
        labelEn: "Claude — tasks & explanations", labelUk: "Claude — завдання й пояснення",
        whatEn: "Claude.ai chat — strong at nuanced grammar explanations, structured drills, and pedagogical scaffolding.",
        whatUk: "Чат Claude.ai — сильний у нюансах граматики, структурованих вправах і педагогічному скаффолдингу.",
        howEn: "Ask Claude to teach in steps, with examples + tests + answer keys. Great for grammar deep-dives.",
        howUk: "Попроси Claude навчати поетапно — з прикладами, тестами й відповідями. Топ для глибокого розбору граматики.",
    },
];

// Student-voice problems per Bloom stage, adapted per aspect.
// Recognisable without knowing the taxonomy.
export const BLOOM_SYMPTOMS = {
    vocabulary: {
        remember:         { en: "\"I recognise the word but cannot recall it.\" · \"I remember the translation but cannot retrieve the word in speech.\" · \"I confuse similar words.\"",
                            uk: "«впізнаю слово, але не можу його пригадати» · «памʼятаю переклад, але не витягую слово у мовленні» · «плутаю схожі слова»" },
        understand:       { en: "\"I know the translation but do not feel the exact meaning.\" · \"I do not know collocations.\" · \"I cannot feel register — formal, casual, rude.\"",
                            uk: "«знаю переклад, але не відчуваю точного значення» · «не знаю колокацій» · «не відчуваю регістр — формальне, неформальне, грубе»" },
        apply_controlled: { en: "\"I do gap-fill well but forget words in real speech.\" · \"I only use new words when the teacher asks.\"",
                            uk: "«вправи з пропусками виконую добре, але забуваю слова в реальному мовленні» · «вживаю нові слова тільки коли викладач просить»" },
        apply_free:       { en: "\"I do not see collocations.\" · \"I do not understand word families.\" · \"I cannot explain the difference between similar words.\"",
                            uk: "«не бачу колокацій» · «не розумію словотвірних родин» · «не можу пояснити різницю між схожими словами»" },
        evaluate:         { en: "\"I choose words by translation, not by situation.\" · \"I do not know which word sounds more professional.\"",
                            uk: "«обираю слова за перекладом, а не за ситуацією» · «не знаю, яке слово звучить професійніше»" },
        create:           { en: "\"I have strong passive vocabulary but speak in basic structures.\" · \"Under pressure I lose new vocabulary.\"",
                            uk: "«маю сильну пасивну лексику, але говорю базовими структурами» · «під тиском втрачаю нову лексику»" },
    },
    listening: {
        remember:         { en: "\"Everything sounds like one word.\" · \"I can't catch where sentences start and end.\"",
                            uk: "«усе звучить як одне слово» · «не чую, де закінчується одне речення й починається інше»" },
        understand:       { en: "\"I get single words but miss the meaning.\" · \"I understand written but not spoken English.\"",
                            uk: "«ловлю окремі слова, але не розумію сенс» · «писане розумію, розмовне — ні»" },
        apply_controlled: { en: "\"I need subtitles to follow.\" · \"If I re-listen 2–3 times I get it.\"",
                            uk: "«без субтитрів не встигаю» · «з 2–3 прослуховувань розумію»" },
        apply_free:       { en: "\"Natives speak too fast for me.\" · \"I zone out after 30 seconds.\"",
                            uk: "«носії говорять надто швидко» · «через 30 секунд губуся»" },
        evaluate:         { en: "\"I miss the nuance — sarcasm, hedging, tone.\" · \"I think I understood, but I missed the main point.\"",
                            uk: "«не ловлю нюанс — сарказм, обережність, тон» · «думав, що зрозумів, але пропустив головне»" },
        create:           { en: "\"I want to follow a podcast / meeting live, no prep.\" · \"Ready to react in real conversations.\"",
                            uk: "«хочу слухати подкаст / зустріч наживо, без підготовки» · «готовий реагувати в реальних розмовах»" },
    },
    reading: {
        remember:         { en: "\"I don't know the vocabulary in this text yet.\" · \"I look up every second word.\"",
                            uk: "«ще не знаю лексику цього тексту» · «заглядаю у словник через слово»" },
        understand:       { en: "\"I read each word but miss the argument.\" · \"I can translate it but can't summarise it.\"",
                            uk: "«читаю слово за словом, але не схоплюю думку» · «можу перекласти, але не можу переказати»" },
        apply_controlled: { en: "\"I can answer comprehension questions when someone asks.\" · \"I need a glossary beside the text.\"",
                            uk: "«відповідаю на питання, коли хтось питає» · «потрібен глосарій поряд»" },
        apply_free:       { en: "\"I only read Ukrainian news — English feels too slow.\" · \"I avoid English articles.\"",
                            uk: "«читаю новини тільки українською — англійською занадто повільно» · «уникаю англомовних статей»" },
        evaluate:         { en: "\"I miss bias, irony, subtext.\" · \"I re-read and find I misunderstood something obvious.\"",
                            uk: "«пропускаю упередженість, іронію, підтекст» · «перечитую і бачу, що зрозумів неправильно очевидне»" },
        create:           { en: "\"I want to read this article to give my team insights tomorrow.\" · \"Ready to work from English sources daily.\"",
                            uk: "«хочу прочитати статтю, щоб завтра розказати команді» · «готовий щодня працювати з англомовними джерелами»" },
    },
    speaking: {
        remember:         { en: "\"I freeze — I don't know the phrases yet.\" · \"I want to hear the phrases first.\"",
                            uk: "«ступор — ще не знаю фраз» · «хочу спочатку почути фрази»" },
        understand:       { en: "\"I know the words but my sentences sound weird.\" · \"I can't tell when to be formal vs casual.\"",
                            uk: "«слова знаю, але речення звучать дивно» · «не розумію, коли бути формальним, а коли ні»" },
        apply_controlled: { en: "\"I speak well when I have a script.\" · \"I need the phrases on a sticky note in front of me.\"",
                            uk: "«зі скриптом — нормально» · «потрібні фрази на стікері»" },
        apply_free:       { en: "\"I know the words but I can't speak.\" · \"I translate in my head — it's slow and clunky.\"",
                            uk: "«знаю слова, але не можу говорити» · «перекладаю в голові — повільно і громіздко»" },
        evaluate:         { en: "\"I say it but it sounds off.\" · \"Natives repeat back my sentence differently — what did I do wrong?\"",
                            uk: "«говорю, а звучить не так» · «носій повторює моє речення по-іншому — що я зробив не так?»" },
        create:           { en: "\"I want to run tomorrow's client call in English.\" · \"Ready to present without reading a script.\"",
                            uk: "«хочу провести завтрашній дзвінок з клієнтом англійською» · «готовий презентувати без скрипту»" },
    },
    writing: {
        remember:         { en: "\"I don't know how this type of email/document is structured.\" · \"Show me examples first.\"",
                            uk: "«не знаю, як структурується такий лист / документ» · «спершу покажіть приклади»" },
        understand:       { en: "\"I understand the parts but don't know the tone.\" · \"Formal vs. friendly — I can't find the balance.\"",
                            uk: "«розумію структуру, але не тон» · «формально vs. дружньо — не можу зловити баланс»" },
        apply_controlled: { en: "\"Give me a template and I'll write.\" · \"Without a template my drafts are rambling.\"",
                            uk: "«дайте шаблон — напишу» · «без шаблону мої чернетки розтягнуті»" },
        apply_free:       { en: "\"I can write but it feels stiff.\" · \"My English emails sound robotic.\"",
                            uk: "«пишу, але виходить сухо» · «мої англійські листи звучать як робот»" },
        evaluate:         { en: "\"I don't see my own errors.\" · \"Grammarly fixes it but I don't know WHY.\"",
                            uk: "«не бачу власних помилок» · «Grammarly виправляє, але не знаю ЧОМУ»" },
        create:           { en: "\"I want to send this escalation email tomorrow.\" · \"Ready to write without drafting in Ukrainian first.\"",
                            uk: "«хочу надіслати цей ескалаційний лист завтра» · «готовий писати одразу англійською, без чернетки українською»" },
    },
    grammar: {
        remember:         { en: "\"I've never seen this structure.\" · \"I want to see it in sentences first.\"",
                            uk: "«ніколи не бачив цієї структури» · «хочу побачити її в реченнях»" },
        understand:       { en: "\"I know the rule but don't feel when to use it.\" · \"Present Perfect vs Past Simple — when is which?\"",
                            uk: "«правило знаю, але не відчуваю, коли вживати» · «Present Perfect vs Past Simple — коли яке?»" },
        apply_controlled: { en: "\"I can do fill-in-the-blank exercises.\" · \"I get it right in drills but fail in conversation.\"",
                            uk: "«вправи з пропусками роблю» · «правильно у дрилах, але провалююсь у розмові»" },
        apply_free:       { en: "\"I know the rules but I break them when I speak.\" · \"I freeze trying to pick the right tense.\"",
                            uk: "«знаю правила, але ламаю їх у мовленні» · «зупиняюсь, обираючи правильний час»" },
        evaluate:         { en: "\"I don't notice my own mistakes.\" · \"Someone corrects me and I see it — but only then.\"",
                            uk: "«не помічаю власних помилок» · «хтось виправляє — і лише тоді бачу»" },
        create:           { en: "\"I want to write/speak tomorrow without second-guessing the tense.\" · \"Ready for this structure to be automatic.\"",
                            uk: "«хочу писати / говорити завтра без сумнівів щодо часу» · «готовий, щоб ця структура стала автоматичною»" },
    },
    translation: {
        remember:         { en: "\"I don't know the English equivalent of many Ukrainian words.\" · \"Show me the pairs first.\"",
                            uk: "«не знаю англійських відповідників багатьом українським словам» · «спершу покажіть пари»" },
        understand:       { en: "\"Word-for-word translation sounds unnatural.\" · \"I don't understand WHY the English version is different.\"",
                            uk: "«дослівний переклад звучить неприродно» · «не розумію, ЧОМУ англійська версія інша»" },
        apply_controlled: { en: "\"Give me phrases and I'll translate them.\" · \"I need context to know which translation to pick.\"",
                            uk: "«дайте фрази — перекладу» · «потрібен контекст, щоб обрати правильний варіант»" },
        apply_free:       { en: "\"I translate in my head and lose the meaning.\" · \"My translations sound like Ukrainian with English words.\"",
                            uk: "«перекладаю в голові і втрачаю сенс» · «мої переклади звучать як українська англійськими словами»" },
        evaluate:         { en: "\"I fall for false friends.\" · \"I translate idioms literally and it sounds absurd.\"",
                            uk: "«попадаюсь на хибні друзі» · «перекладаю ідіоми дослівно і звучить безглуздо»" },
        create:           { en: "\"I want to switch between Ukrainian and English in the same meeting.\" · \"Ready to interpret for a colleague.\"",
                            uk: "«хочу перемикатись між мовами на одній зустрічі» · «готовий перекласти колезі»" },
    },
    custom: {
        remember:         { en: "\"I'm new to this — show me the basics.\"",
                            uk: "«я новачок у цьому — покажіть основи»" },
        understand:       { en: "\"I see it but the logic isn't clear.\"",
                            uk: "«бачу, але логіка незрозуміла»" },
        apply_controlled: { en: "\"I can do it with support but not alone.\"",
                            uk: "«можу з підтримкою, сам — ні»" },
        apply_free:       { en: "\"I need to move from theory to actual use.\"",
                            uk: "«треба перейти від теорії до практики»" },
        evaluate:         { en: "\"I keep making the same mistakes without noticing.\"",
                            uk: "«роблю ті самі помилки, не помічаючи»" },
        create:           { en: "\"I want to use it in a real situation this week.\"",
                            uk: "«хочу використати в реальній ситуації цього тижня»" },
    },
};

// Step-by-step paste instructions per activity, in each language.
// Rendered as a numbered list in the prompt card.
export const PASTE_STEPS = {
    audio_retelling: {
        en: ["Open notebooklm.google.com and sign in with Google.", "Create a new notebook (or open your existing one).", "Add at least one source (the material you used, or the one generated by the prep-prompt).", "Click the chat field at the bottom and paste the prompt.", "When the chat responds, go to the Studio panel → click \"Audio Overview\" → Generate.", "Listen to the podcast, then follow the After-section reflection."],
        uk: ["Відкрий notebooklm.google.com і увійди через Google.", "Створи новий notebook (або відкрий існуючий).", "Додай хоча б одне джерело (твій матеріал або той, що згенерував prep-промт).", "Натисни на поле чату внизу і встав промт.", "Коли чат відповість, перейди в панель Studio → «Audio Overview» → Generate.", "Послухай подкаст, потім виконай рефлексію з After-секції."],
    },
    video_retelling: {
        en: ["Open NotebookLM, create or open a notebook.", "Add your source(s).", "Paste the prompt into the chat.", "After the chat responds, open Studio → \"Video Overview\" → Generate.", "Watch without subtitles first, then with.", "Do the After-reflection."],
        uk: ["Відкрий NotebookLM, створи або відкрий notebook.", "Додай джерело(а).", "Встав промт у чат.", "Після відповіді чату відкрий Studio → «Video Overview» → Generate.", "Дивись спочатку без субтитрів, потім із.", "Виконай After-рефлексію."],
    },
    mind_map: {
        en: ["Open NotebookLM, create or open a notebook.", "Add your source(s).", "Paste the prompt into the chat.", "Open Studio panel → click \"Mind Map\" → Generate.", "Click each node to expand — use those branches as speaking prompts."],
        uk: ["Відкрий NotebookLM, створи або відкрий notebook.", "Додай джерело(а).", "Встав промт у чат.", "Відкрий Studio → «Mind Map» → Generate.", "Натискай на вузли, щоб розгорнути — використовуй гілки як теми для говоріння."],
    },
    flashcards: {
        en: ["Open NotebookLM, create or open a notebook.", "Add your source(s).", "Paste the prompt into the chat — specify the format you want (term ↔ translation, term ↔ definition, or sentence with a gap).", "Click Studio → \"Flashcards\" → Generate.", "Study with active recall: L1 front → try English → flip."],
        uk: ["Відкрий NotebookLM, створи або відкрий notebook.", "Додай джерело(а).", "Встав промт у чат — вкажи потрібний формат (слово ↔ переклад, слово ↔ означення, речення з пропуском).", "Натисни Studio → «Flashcards» → Generate.", "Вчи з активним відтворенням: українська спереду → спробуй англійську → переверни."],
    },
    test: {
        en: ["Open NotebookLM, create or open a notebook.", "Add your source(s).", "Paste the prompt into the chat.", "Click Studio → \"Quiz\" → Generate.", "Take the quiz without notes.", "Review wrong answers as your gap list."],
        uk: ["Відкрий NotebookLM, створи або відкрий notebook.", "Додай джерело(а).", "Встав промт у чат.", "Натисни Studio → «Quiz» → Generate.", "Пиши тест без нотаток.", "Переглянь помилки — це твій список прогалин."],
    },
    infographic: {
        en: ["Open NotebookLM Studio → select \"Infographic\".", "In the description box, paste the prompt as your instructions.", "Generate. Download the PNG/PDF.", "Pin it to your desktop as a quick-reference before meetings."],
        uk: ["Відкрий NotebookLM Studio → вибери «Infographic».", "У полі опису встав промт як інструкцію.", "Згенеруй. Завантаж PNG/PDF.", "Закріпи на робочому столі як швидкий нагадник перед зустрічами."],
    },
    study_guide: {
        en: ["Open NotebookLM Studio → Reports → \"Custom Format\".", "Paste the prompt as the format instructions.", "Click Generate. Save as PDF or Markdown.", "Read-through, then close it and reproduce key phrases out loud."],
        uk: ["Відкрий NotebookLM Studio → Reports → «Custom Format».", "Встав промт як інструкцію для формату.", "Натисни Generate. Збережи як PDF або Markdown.", "Прочитай, закрий і відтвори ключові фрази вголос."],
    },
    presentation: {
        en: ["Open NotebookLM Studio → \"Presentation\".", "In the \"Extra instructions\" field, paste the prompt.", "Generate the slide deck.", "Rehearse presenting it aloud, record yourself, review."],
        uk: ["Відкрий NotebookLM Studio → «Presentation».", "У полі «Extra instructions» встав промт.", "Згенеруй слайди.", "Тренуйся презентувати вголос, запиши себе, перевір."],
    },
    roleplay: {
        en: ["Open chat.openai.com or gemini.google.com.", "Paste the entire prompt in the chat field.", "Where the prompt says \"[Paste your phrases here]\", paste phrases you collected from NotebookLM.", "Send. The AI will assume the role you specified.", "Respond in English — speak aloud if you can (voice mode)."],
        uk: ["Відкрий chat.openai.com або gemini.google.com.", "Встав увесь промт у поле чату.", "Там, де сказано «[Paste your phrases here]», встав фрази з NotebookLM.", "Надішли. AI візьме на себе роль, яку ти вказав.", "Відповідай англійською — якщо можеш, говори вголос (voice mode)."],
    },
    speak_voice: {
        en: ["ChatGPT: tap the voice-wave icon (mobile app or web). Gemini: open Gemini Live.", "Start the voice session.", "Paste the prompt into the pre-session text field, or read it aloud to Claude/ChatGPT first, then go voice.", "Speak. Ask the AI to gently correct pronunciation/grammar.", "Review the transcript afterwards for patterns."],
        uk: ["ChatGPT: натисни іконку голосу (мобільний додаток або веб). Gemini: відкрий Gemini Live.", "Почни голосову сесію.", "Встав промт у текстове поле перед сесією, або прочитай його вголос ChatGPT/Claude, тоді переходь у голос.", "Говори. Попроси AI мʼяко виправляти вимову/граматику.", "Пізніше переглянь транскрипт — шукай патерни."],
    },
    write_feedback: {
        en: ["Open ChatGPT or Gemini chat.", "Paste the prompt.", "Follow the Before-section: write your draft first.", "Send it to the AI with the During-section instruction to mark line-by-line corrections.", "Compare the AI's rewrite vs your draft and note 3 patterns."],
        uk: ["Відкрий ChatGPT або Gemini.", "Встав промт.", "Виконай Before-секцію: спочатку напиши свою чернетку.", "Надішли AI разом з During-інструкцією про правки рядок-за-рядком.", "Порівняй свій варіант із переписаним і виділи 3 патерни."],
    },
    claude_chat: {
        en: ["Open claude.ai and start a new chat.", "Paste the prompt.", "Work through Before → During → After in one thread — Claude keeps context.", "If you have phrases from NotebookLM, paste them when the prompt says so."],
        uk: ["Відкрий claude.ai і почни новий чат.", "Встав промт.", "Пройди Before → During → After у одному треді — Claude тримає контекст.", "Якщо є фрази з NotebookLM, встав їх, коли промт це вкаже."],
    },
};

// Recommendations: aspect+stage -> array of activity ids highlighted in green.
export const RECOMMENDATIONS = {
    vocabulary: {
        remember: ["flashcards", "audio_retelling"],
        understand: ["audio_retelling", "mind_map", "claude_chat"],
        apply_controlled: ["flashcards", "claude_chat", "write_feedback"],
        apply_free: ["roleplay", "write_feedback"],
        evaluate: ["test", "claude_chat"],
        create: ["roleplay", "speak_voice"],
    },
    listening: {
        remember: ["audio_retelling", "video_retelling"],
        understand: ["audio_retelling", "video_retelling", "mind_map"],
        apply_controlled: ["audio_retelling", "claude_chat"],
        apply_free: ["video_retelling", "speak_voice"],
        evaluate: ["test", "claude_chat"],
        create: ["speak_voice", "roleplay"],
    },
    reading: {
        remember: ["mind_map", "study_guide"],
        understand: ["study_guide", "mind_map", "claude_chat"],
        apply_controlled: ["claude_chat", "test"],
        apply_free: ["write_feedback", "presentation"],
        evaluate: ["test", "claude_chat"],
        create: ["presentation", "infographic"],
    },
    speaking: {
        remember: ["audio_retelling", "video_retelling"],
        understand: ["video_retelling", "claude_chat"],
        apply_controlled: ["roleplay", "claude_chat"],
        apply_free: ["speak_voice", "roleplay"],
        evaluate: ["roleplay", "speak_voice"],
        create: ["speak_voice", "roleplay"],
    },
    writing: {
        remember: ["study_guide", "claude_chat"],
        understand: ["study_guide", "claude_chat"],
        apply_controlled: ["write_feedback", "claude_chat"],
        apply_free: ["write_feedback", "presentation"],
        evaluate: ["write_feedback", "claude_chat"],
        create: ["write_feedback", "presentation"],
    },
    grammar: {
        remember: ["claude_chat", "flashcards"],
        understand: ["claude_chat", "study_guide"],
        apply_controlled: ["claude_chat", "test"],
        apply_free: ["write_feedback", "roleplay"],
        evaluate: ["test", "claude_chat"],
        create: ["write_feedback", "speak_voice"],
    },
    translation: {
        remember: ["flashcards", "claude_chat"],
        understand: ["claude_chat", "study_guide"],
        apply_controlled: ["claude_chat", "write_feedback"],
        apply_free: ["write_feedback", "claude_chat"],
        evaluate: ["claude_chat", "test"],
        create: ["write_feedback", "presentation"],
    },
    custom: {
        remember: ["claude_chat"],
        understand: ["claude_chat", "study_guide"],
        apply_controlled: ["claude_chat", "write_feedback"],
        apply_free: ["claude_chat", "speak_voice"],
        evaluate: ["claude_chat", "test"],
        create: ["claude_chat", "presentation"],
    },
};
